language: php

env:
    global:
        - MIN_PHP=7.2.5
        - SYMFONY_PHPUNIT_DISABLE_RESULT_CACHE=1

matrix:
    include:
        - php: 7.2
          env: php_extra="7.4"
        - php: 7.3
          env: deps=high
        - php: 7.4
          env: deps=low
    fast_finish: true

install:
    - composer install
